### ISSUE TITLE
docker build failed with bytes out of the expected range.

### ISSUE THREAD

**Issue by kikigith** [sitya/samlidp#15]
Hello, 
I'm trying to deploy samlidp. 
The samli/nren image's build failed with the following error:

kiki@hero:~/samlidp$ sudo docker build -t samli/nren .
Sending build context to Docker daemon  6.577MB
.......
Do not run Composer as root/super user! See https://getcomposer.org/root for details
Loading composer repositories with package information
Updating dependencies
[Composer\Downloader\TransportException]                                    
  Content-Length mismatch, received 577487 bytes out of the expected 1929588  
                                                                              

install [--prefer-source] [--prefer-dist] [--dry-run] [--dev] [--no-dev] [--no-custom-installers] [--no-autoloader] [--no-scripts] [--no-progress] [--no-suggest] [-v|vv|vvv|--verbose] [-o|--optimize-autoloader] [-a|--classmap-authoritative] [--apcu-autoloader] [--ignore-platform-reqs] [--] [<packages>]...

The command '/bin/sh -c cd /app && php -d memory_limit=-1 /usr/bin/composer install --no-autoloader --no-interaction --no-scripts --no-dev' returned a non-zero code: 1

What is wrong?

Thank you.

**Comment by sitya** [comment]
I have tried to reproduce the problem, it has been built fine based on the latest commit, so sorry, I do not know, what could be wrong on your side.
